spring:
  docker:
    compose:
      stop:
        command: down

jwt:
  access-token-key: '{"kty": "oct", "k": "MEKCIovr7LkgBVclCJrY0ob7PPq9f2bUvZQdksNiD17dseHybaswEbFWXhKk0dN"}'
  refresh-token-key: '{"kty": "oct", "k": "y5Z9GPBPa6P9LyiO7haVOu0If0BCMGfHqX48NNthPhDS4D39X4AzZzjGZ3E5e43"}'
#  m - minutes
#  h - hours
#  d - days
  access-token-expiration: "15m"
  refresh-token-expiration: "30d"
logging:
  level:
    org.springframework.security: trace
