spring:
  docker:
    compose:
      stop:
        command: down
  jpa:

    hibernate:
      ddl-auto: create-drop


jwt:
  access-token-key: '{"kty": "oct", "k": "3eb97465e14c1dafb0f287da7651b683272a4bf7d802dc46a8c1c8fa2386fcea"}'
  refresh-token-key: '{"kty": "oct", "k": "d4434ef0590e8335919ebb0de4d6068c"}'
#  m - minutes
#  h - hours
#  d - days
  access-token-expiration: "15m"
  refresh-token-expiration: "30d"
logging:
  level:
    org.springframework.security: trace
